version: '3'

services:

  backend:
    build: ./
    container_name: backend
    restart: always
    command: ./commands/${RUN_MODE}.sh
    ports:
      - ${WSGI_PORT}:${WSGI_PORT}
    volumes:
      - ./src:/opt/project
      - ./commands:/opt/project/commands
      - static_content:/var/www/tmb
#    env_file:
#      - ./src/app/settings/.env
#    env_file:
            #      - .env
    depends_on:
      - postgresql
#      - celery

  postgresql:
    image: "postgres:12"
    container_name: postgresql
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    env_file:
      - .env
    image: nginx:1.18-alpine
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_content:/var/www/tmb
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend



volumes:
  pgdata: {}
  static_content: {}
  media_content: {}
