version: '3'

services:

  backend:
    build: ./
    restart: always
    command: ./commands/${RUN_MODE}.sh
    ports:
      - ${WSGI_PORT}:${WSGI_PORT}
#    environment:
#      - DJANGO_SETTINGS_MODULE=app.settings.${RUN_MODE}
    volumes:
      - ./src:/opt/project
      - ./commands:/opt/project/commands
      - static_content:/var/www/project
    env_file:
      - .env
    depends_on:
      - postgresql

  postgresql:
    image: postgres:12
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    env_file:
      - .env
    image: nginx:1.18-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_content:/var/www/project
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend


volumes:
  pgdata: {}
  static_content: {}
  media_content: {}
